### ISSUE TITLE
Perl sample shows Managed VMs, not Google Cloud App Engine Flexible Environment

### ISSUE THREAD

**Issue by bradfitz** [GoogleCloudPlatform/appengine-custom-runtimes-samples#13]
The "Perl" link at https://cloudplatform.googleblog.com/2017/03/your-favorite-languages-now-on-Google-App-Engine.html points to:

https://github.com/GoogleCloudPlatform/appengine-custom-runtimes-samples/tree/master/perl

Which says:

```
runtime: custom
vm: true
```

... which is Managed VMs, not the new Google Cloud App Engine Flexible Environment.

(But the app.yaml in that repo correctly has `env: flex`)

**Comment by jonparrott** [comment]
Fix by 3df0748
