### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jorge0136** [GoogleCloudPlatform/appengine-custom-runtimes-samples#21]
What is the status of this project? Is the repo abandoned? There are multiple PRs open without any feedback, issues in similar state.

This repo is still actively referenced in google documentation. If this repo is being deprecated can we please reflect that elsewhere?

**Comment by grant** [comment]
Hi there. The samples should still work.

If there are issues with any specific sample, please file an issue or PR! I merged many of the open PRs just now.
